spring.application.name=BuyMeal

server.port=${PORT:8080}

# SQL Logging
# spring.jpa.show-sql=true
# Show SQL in readable way
# Spring.jpa.properties.hibernate.format_sql=true
 
 
# To Enable the H2 Database
#spring.h2.console.enabled = true
# To provide the source of the H2 Database
#spring.datasource.url= jdbc:h2:mem:ticket

# h2 configuration pom.xml
#		<dependency>
#			<groupId>com.h2database</groupId>
#			<artifactId>h2</artifactId>
#			<scope>runtime</scope>
#		</dependency>

# Connection String :   postgresql://postgres:java@541816450280106@db.avrtccqclocictlkdnwt.supabase.co:5432/postgres

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.avrtccqclocictlkdnwt
spring.datasource.password=java@541816450280206

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.data-source-properties.sslmode=require


spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=3

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.jdbc.use_streams_for_lob=true